---
title: "Pead"
author: "Contentio d.o.o."
date: "7/8/2021"
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
params:
  predictions: preds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, echo=FALSE, message=FALSE)

library(data.table)
library(kableExtra)
```

```{r}
# nice table
mltbl <- data.table::melt(predictions,
                          id.vars = c("symbol", "event_date"),
                          measure.vars = patterns("classif"),
                          variable.factor = FALSE)
mltbl[, model := gsub(".*\\.", "", variable)]
mltbl[, prediction := ifelse(grep("response", variable), value, NA), by = model]
mltbl <- mltbl[!grepl("response", variable)]
mltbl[, variable := gsub("_class.*", "", variable)]
mltbl <- as.data.table(pivot_wider(mltbl, names_from = variable))
cols <- colnames(mltbl)[5:7]
mltbl[, (cols) := lapply(.SD, function(x) round(as.numeric(x), 2)), .SDcols = cols]
kable(mltbl, align = "c") %>%
  kableExtra::kable_styling(full_width = FALSE)
```

