---
title: "PEAD"
author: "Mislav Sagovac"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output: html_document
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
params:
  lean_path: 'C:/Users/Mislav/Documents/GitHub/Lean/Results'
  algortihm_name: ExuberAlgorithm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, echo=FALSE, message=FALSE)

library(tidyr)
library(jsonlite)
library(kableExtra)
library(purrr)
library(data.table)
library(ggplot2)
library(PerformanceAnalytics)
```


```{r include=FALSE}
# nice table
mltbl <- data.table::melt(predictions, 
                          id.vars = c("symbol", "event_date"), 
                          measure.vars = patterns("classif"),
                          variable.factor = FALSE)
mltbl[, model := gsub(".*\\.", "", variable)]
mltbl[, prediction := ifelse(grep("response", variable), value, NA), by = model]
mltbl <- mltbl[!grepl("response", variable)]
mltbl <- mltbl[, .(symbol, event_date, model, prediction, value)]
kbl(mltbl, align = "c") %>% 
  kable_paper(full_width = FALSE) %>% 
  column_spec(1, bold = TRUE) %>% 
  collapse_rows(columns = 1:2, valign = "top")
```
