---
title: "prepare"
author: "Contentio d.o.o."
date: '12 11 2020 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{r setup}
library(data.table)
library(xts)
library(quantmod)
library(fmlr)
library(tseries)
library(data.table)
library(reticulate)
source('R/import_data.R')
source('R/features.R')
source('R/outliers.R')
# python packages
py <- reticulate::use_python('C:/ProgramData/Anaconda3')
# ml <- reticulate::import('mlfinlab')
# pd <- reticulate::import('pandas')
```


```{r pressure, echo=FALSE}
# Parameters
de_prado_fracdiff = TRUE
filtering = 'cusum'
```


```{r}
# Import
market_data <- import_mysql(
  contract = 'SPY_IB',
  save_path = 'D:/market_data/usa/ohlcv',
  RMySQL::MySQL(),
  dbname = 'odvjet12_market_data_usa',
  username = 'odvjet12_mislav',
  password = 'Theanswer0207',
  host = '91.234.46.219'
)
```

```{r}
# convert to xts
market_data_xts <- xts::xts(market_data[, 2:(ncol(market_data)-1)], order.by = market_data$date)

# Remove outliers
market_data_xts <- remove_outlier_median(quantmod::OHLC(market_data_xts), median_scaler = 25)

# Add features
market_data_xts <- add_features(market_data_xts)

# Remove constant columns (from https://stackoverflow.com/questions/15068981/removal-of-constant-columns-in-r)
market_data_xts <- market_data_xts[,!apply(market_data_xts, MARGIN = 2, function(x) max(x, na.rm = TRUE) == min(x, na.rm = TRUE))]

# close (for ptrhon chunk)
close <- as.data.table(market_data_xts$close)
close
```


```{python}
import pandas as pd
import mlfinlab as ml

close = r.close
close.index = close['index']
close.
# close = pd.Series(close['close'], index=close['index'])
close.tail()
```

